### ISSUE TITLE
Sorry!

### ISSUE THREAD

**Issue by satoshi88** [Codehardt/aao-sdplugin-fcu#1]
Hello Codehardt and thank you for your work. Since I have the flight simulator, I have wished for exactly that. Unfortunately, it does not work for me. All other scripts (from flightsim.to) run without problems. The FCU is in the JS folder and the files are edited with notepad++. In the display above the knobs it says only FCU1, FCU2,... . Even while the flight simulator is running. Is there any other requirement for it to work? 

Many thanks and greetings from Hamburg
![Stream Deck +](https://user-images.githubusercontent.com/122312570/211397557-cac86d17-5947-434e-b649-db05f1c29de5.jpg)

**Comment by Codehardt** [comment]
hey @satoshi88,

another user had the same issue that had been caused by the wrong file extension of the `fcu.js`. The file was accidently created as `fcu.js.txt` instead of `fcu.js`. How did you create the `fcu.js`? Right-click -> create new text file? Maybe your file name is `fcu.js.txt`, too. You can check this by enabling the file extensions in the file explorer:

![Screenshot 2023-01-10 165432](https://user-images.githubusercontent.com/15139137/211599865-8b73b547-0761-4938-8899-fe81be31c01e.png)

Since you're living in Hamburg, you should be fine with a german screenshot I guess.

If you are sure that the file extension is correct, you can send me your patched `code.html` and `aaoDeck.js`, then I can validate your applied changes.

What version of AAO plugin for StreamDeck do you use? I tested it with version 14.19.

Do you use the FlyByWire A32NX project?

Kind regards,
Marcel

**Comment by satoshi88** [comment]
Hallo Marcel,

dann können wir glaube ich, auch auf deutsch schreiben. :) Erstmal vielen Dank für deine Antwort, ich wusste die Hilfe sehr zu schätzen. Mein Problem war tatsächlich die FCU-Datei. Nach deinem Hinweis, habe ich sie mir nochmal genau angesehen. Der Inhalt kam mir komisch vor und sie war auch etwas groß (400KB). Ich hatte sie von github heruntergeladen (Ziel speichern unter...) und habe jetzt stattdessen nur den Code kopiert und den vorhandenen überschrieben. Jetzt funktioniert alles bestens. Nochmal meinen allerherzlichsten Dank für deine Arbeit! Ich hab mir sowas immer gewünscht und es macht sehr viel Spaß.

Viele Grüße
Robert :)
